/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puntoventa;

/**
 *
 * @author ASUS
 */
public class venta extends javax.swing.JFrame {

    // inicializacion de la lista qeu almacenara datos 
    String[] prodL = new String[40];
    int a = 0;

    /**
     * Creates new form venta
     */
    public venta() {
        initComponents();
        this.setTitle("Venta de Productos ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        txtstock = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        lblstock = new javax.swing.JLabel();
        lblprecio = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtbusqueda = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bwtnbuscar1 = new org.edisoncor.gui.button.ButtonTask();
        btnagregar = new org.edisoncor.gui.button.ButtonTask();
        lbldatocantidad = new javax.swing.JLabel();
        btnregresar = new org.edisoncor.gui.button.ButtonTask();
        btngenerarF = new org.edisoncor.gui.button.ButtonTask();
        txtcantidadV = new javax.swing.JTextField();
        JOptionPane1 = new javax.swing.JOptionPane();
        lbltxtiva = new javax.swing.JLabel();
        lbltxttotal = new javax.swing.JLabel();
        lbltxtsubtotal = new javax.swing.JLabel();
        lbltotal = new javax.swing.JLabel();
        lbliva = new javax.swing.JLabel();
        lbsub = new javax.swing.JLabel();
        txtdetalleF = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableF = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        mostrarV = new javax.swing.JButton();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Buscar");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BUSQUEDA DE PRODUCTOS", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("LCD", 1, 36), new java.awt.Color(51, 96, 38))); // NOI18N

        txtstock.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        txtstock.setForeground(new java.awt.Color(255, 255, 255));
        txtstock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puntoventa/img/worker-loading-boxes.png"))); // NOI18N
        txtstock.setText("Stock ");

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puntoventa/img/money.png"))); // NOI18N
        jLabel5.setText("Precio");

        lblnombre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblnombre.setForeground(new java.awt.Color(255, 255, 255));

        lblstock.setBackground(new java.awt.Color(0, 0, 0));
        lblstock.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblstock.setForeground(new java.awt.Color(255, 255, 255));

        lblprecio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblprecio.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("$");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingrese el nombre del producto: ");

        txtbusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbusquedaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puntoventa/img/producto.png"))); // NOI18N
        jLabel3.setText("Nombre Producto ");

        bwtnbuscar1.setForeground(new java.awt.Color(255, 255, 255));
        bwtnbuscar1.setText("Buscar");
        bwtnbuscar1.setDescription("..............");
        bwtnbuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bwtnbuscar1ActionPerformed(evt);
            }
        });

        btnagregar.setBackground(new java.awt.Color(255, 255, 255));
        btnagregar.setForeground(new java.awt.Color(255, 255, 255));
        btnagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puntoventa/img/shopping-cart-verified-symbol_icon-icons.com_56123.png"))); // NOI18N
        btnagregar.setText("Agregar al carrito ");
        btnagregar.setDefaultCapable(false);
        btnagregar.setDescription("-----------------");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });

        lbldatocantidad.setForeground(new java.awt.Color(255, 255, 255));

        btnregresar.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 1, 4, 2));
        btnregresar.setForeground(new java.awt.Color(255, 255, 255));
        btnregresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puntoventa/img/menuV.png"))); // NOI18N
        btnregresar.setText("Regresar al Menu");
        btnregresar.setDescription("____________________");
        btnregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresarActionPerformed(evt);
            }
        });

        btngenerarF.setBackground(new java.awt.Color(255, 255, 255));
        btngenerarF.setForeground(new java.awt.Color(255, 255, 255));
        btngenerarF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puntoventa/img/calculator.png"))); // NOI18N
        btngenerarF.setText("Generar Factura");
        btngenerarF.setToolTipText("calculo precio");
        btngenerarF.setDefaultCapable(false);
        btngenerarF.setDescription("------------------------------");
        btngenerarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngenerarFActionPerformed(evt);
            }
        });

        txtcantidadV.setBackground(new java.awt.Color(240, 240, 240));
        txtcantidadV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantidadVActionPerformed(evt);
            }
        });

        JOptionPane1.setBackground(new java.awt.Color(155, 66, 66));
        JOptionPane1.setBorder(null);
        JOptionPane1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puntoventa/img/falla.png"))); // NOI18N
        JOptionPane1.setMessage(JOptionPane1.getName());

        lbltxtiva.setBackground(new java.awt.Color(0, 153, 0));
        lbltxtiva.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbltxtiva.setForeground(new java.awt.Color(255, 255, 255));

        lbltxttotal.setBackground(new java.awt.Color(0, 153, 0));
        lbltxttotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbltxttotal.setForeground(new java.awt.Color(255, 255, 255));
        lbltxttotal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puntoventa/img/pay.png"))); // NOI18N

        lbltxtsubtotal.setBackground(new java.awt.Color(0, 153, 0));
        lbltxtsubtotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbltxtsubtotal.setForeground(new java.awt.Color(255, 255, 255));

        lbltotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbltotal.setForeground(new java.awt.Color(255, 255, 255));

        lbliva.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbliva.setForeground(new java.awt.Color(255, 255, 255));

        lbsub.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbsub.setForeground(new java.awt.Color(255, 255, 255));

        txtdetalleF.setBackground(new java.awt.Color(255, 255, 255));
        txtdetalleF.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        txtdetalleF.setForeground(new java.awt.Color(255, 255, 255));

        tableF.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableF.setRowHeight(30);
        tableF.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                tableFComponentAdded(evt);
            }
        });
        jScrollPane2.setViewportView(tableF);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puntoventa/img/buscador.gif"))); // NOI18N

        mostrarV.setBackground(new java.awt.Color(0, 153, 0));
        mostrarV.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mostrarV.setText("Mostrar Stock Productos Existentes ");
        mostrarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lbltxtsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltxtiva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbltxttotal, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbltotal, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(lbliva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbsub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbldatocantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(45, 45, 45)
                                        .addComponent(txtcantidadV, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(101, 101, 101)
                                        .addComponent(txtstock))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(338, 338, 338)
                                        .addComponent(lblstock, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(145, 145, 145)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bwtnbuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addComponent(btngenerarF, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(134, 134, 134)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(txtdetalleF, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(69, 69, 69)
                        .addComponent(txtbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(mostrarV)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(bwtnbuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtstock)
                            .addComponent(jLabel5))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblstock, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnagregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btngenerarF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbldatocantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtcantidadV, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addComponent(txtdetalleF, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbsub, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                            .addComponent(lbltxtsubtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(mostrarV, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbliva, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                            .addComponent(lbltxtiva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbltotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbltxttotal, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(btnregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void bwtnbuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bwtnbuscar1ActionPerformed

        String nombre_a_buscar = txtbusqueda.getText();
        lblnombre.setText("No existe el producto.");
        for (Producto p : Registro.product) {
            /* verificamos que el nombre a buscar este contenido
             dentro del nombre del producto
             contains compara la similitud de un texto con otro */
            
            if (p.getNombre().contains(nombre_a_buscar)) {

                // accede al nombre del objeto y lo muestra
                lblnombre.setText(p.getNombre());
                lblstock.setText(String.valueOf(p.getCantidad()));
                lblprecio.setText(String.valueOf(p.getPrecio()));

            } else if ("No existe el producto." == lblnombre.getText()) {
                limpiar();

            }

        }

    }//GEN-LAST:event_bwtnbuscar1ActionPerformed

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        // TODO add your handling code here:
        // Declaracion de variables que almacenan los valores de entrada

        Integer stock = Integer.parseInt(lblstock.getText());
        if (lblnombre.getText().equals("No existe el producto.")) {
            limpiar();
        } else if (stock != 0) {
            lbldatocantidad.setText("Ingrese la cantidad que desea");

        }


    }//GEN-LAST:event_btnagregarActionPerformed


    private void btnregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresarActionPerformed
        // TODO add your handling code here:

        menu me = new menu();
        me.show();
    }//GEN-LAST:event_btnregresarActionPerformed
    // Inicializacion de variables globales 
    double subtotal = 0;
    double iva;
    double total;
    int stock;
    int j = 0;
    String matriz[][] = new String[40][10];
    private java.text.DecimalFormat formato = new java.text.DecimalFormat("0.00");
    private void btngenerarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngenerarFActionPerformed
        // TODO add your handling code here:
        // limpia el valor que contiene el TextField 
        lbldatocantidad.setText("");

        // obtiene el valor del cajon de busqueda
        String nomBuscar = txtbusqueda.getText();

        // se lo hace visible al momento de presionar el boton de generar la factura
        jScrollPane2.setVisible(true);

        // Recorrer la lista de objetos
        for (Producto p : Registro.product) {
            // Comparar si existe 
            if (p.getNombre().contains(nomBuscar)) {

                // Comparacion si el stock es mayor a al cantidad que desea comprar
                if (Integer.parseInt(txtcantidadV.getText()) <= p.getCantidad()) {
                    subtotal = subtotal + Integer.parseInt(txtcantidadV.getText())
                            * Double.parseDouble(lblprecio.getText());
                    // Calculo del iva 
                    iva = subtotal * 0.12;
                    // Actualizacion de la variable cantidad, restandole al cantidad comprsda
                    p.setCantidad(p.getCantidad() - Integer.parseInt(txtcantidadV.getText()));

                    // Matriz que me permite mostrar ls valores en una tabla para la factura
                    matriz[j][0] = lblnombre.getText();
                    // Obtencion de los datos a mostrar
                    matriz[j][1] = String.valueOf(txtcantidadV.getText());
                    matriz[j][2] = String.valueOf(lblprecio.getText());
                    matriz[j][3] = String.valueOf(formato.format(Integer.parseInt(txtcantidadV.getText())
                            * Double.parseDouble(lblprecio.getText())));
                    // Aumento del contador
                    j++;
                    // Metodo para la tabla 
                    tableF.setModel(new javax.swing.table.DefaultTableModel(
                            matriz,
                            new String[]{
                                // Encabezadosde las columnas de la tabla 
                                "Nombre Producto", "Cantidad", "Precio Unitario",
                                "Subtotal Product."
                            }
                    ));
                    // Limpiar los lbl y txt
                    limpiar();
                    // Escribir valores de salida de la factura
                    lbltxtsubtotal.setText("Subtotal: ");
                    lbltxttotal.setText("Total:");
                    lbltxtiva.setText("Iva: ");
                    txtdetalleF.setText(" DETALLE FACTURA ");

                    // Se llama al formato para la impresion de dos decimales no mas de 2
                    lbsub.setText(String.valueOf(formato.format(subtotal)));
                    lbliva.setText(String.valueOf(formato.format(iva)));
                    total = subtotal + iva;
                    lbltotal.setText(String.valueOf(formato.format(total)));

                } else {
                    // Mensaje de salida cuando ingresa valores mayores al de Stock
                    JOptionPane1.showMessageDialog(null, "Ingrese una "
                            + "cantidad menor al Stock Existente ");

                }

            }

        }

    }//GEN-LAST:event_btngenerarFActionPerformed

    public void limpiar() {
        // vaciar los labet y los txt cuando se compra un producto
        lblstock.setText("");
        lblprecio.setText("");
        txtcantidadV.setText("");
       
    }


    private void txtbusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbusquedaActionPerformed

    private void txtcantidadVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantidadVActionPerformed
        // TODO add your handling code here:
        // Aplicarle enable apra desabilitar ls cajas de texto
    }//GEN-LAST:event_txtcantidadVActionPerformed

    private void tableFComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_tableFComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tableFComponentAdded

// Boton que me permite mostrar el Stock existente de productos para que el
    private void mostrarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarVActionPerformed
        // TODO add your handling code here:

        // permite Mostrar la lista del Stock Existente nombre y cantidad
        String cadena = "------------";
        for (Producto p : Registro.product) {
            prodL[a] = p.getNombre() + "            "
                    + p.getCantidad();
            a++;


    }//GEN-LAST:event_mostrarVActionPerformed
        JOptionPane1.showMessageDialog(null, prodL);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new venta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JOptionPane JOptionPane1;
    private org.edisoncor.gui.button.ButtonTask btnagregar;
    private org.edisoncor.gui.button.ButtonTask btngenerarF;
    private org.edisoncor.gui.button.ButtonTask btnregresar;
    private org.edisoncor.gui.button.ButtonTask bwtnbuscar1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    public javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbldatocantidad;
    private javax.swing.JLabel lbliva;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblprecio;
    private javax.swing.JLabel lblstock;
    private javax.swing.JLabel lbltotal;
    private javax.swing.JLabel lbltxtiva;
    private javax.swing.JLabel lbltxtsubtotal;
    private javax.swing.JLabel lbltxttotal;
    private javax.swing.JLabel lbsub;
    private javax.swing.JButton mostrarV;
    public javax.swing.JTable tableF;
    private javax.swing.JTextField txtbusqueda;
    private javax.swing.JTextField txtcantidadV;
    private javax.swing.JLabel txtdetalleF;
    private javax.swing.JLabel txtstock;
    // End of variables declaration//GEN-END:variables
}
